services:
  backend:
    build: .
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=myuser
      - FLASK_DB_PASSWORD=mypassword
      - FLASK_DB_NAME=mydb
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
    ports:
      - "5000"
    depends_on:
      - postgres
    restart: always
    networks:
      - mynet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./nginx:/etc/nginx
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx
      - ./frontend/build:/usr/share/nginx/html

  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: always
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet: