services:
  backend:
    build: .
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=myuser
      - FLASK_DB_PASSWORD=mypassword
      - FLASK_DB_NAME=mydb
      - FLASK_DB_HOST=postgres
      - FLASK_DB_PORT=5432
    ports:
      - "5000"
    depends_on:
      - postgres
    restart: always
    networks:
      - mynet
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    command: python run.py

  frontend:
    build: ./frontend
    command: npm run build
    volumes:
      - ./frontend:/app
    depends_on:
      - nginx

  nginx-frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend

  nginx-backend:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  postgres:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    restart: always
    networks:
      - mynet

volumes:
  db-data:

networks:
  mynet: